import { appInfo } from '../../lib/app-info';

export function Footer() {
  return (
    <footer className="border-t border-border">
      <div className="mx-auto flex w-full max-w-5xl flex-wrap items-center justify-between gap-2 px-4 py-4 text-xs text-muted-foreground">
        <span>
          {appInfo.title} · mode: {appInfo.mode}
        </span>
        <span>Generated by the Platform MFE Application template</span>
      </div>
    </footer>
  );
}
