import { createFileRoute, Link } from '@tanstack/react-router';

import {
  useAuth,
  useNavigation,
  usePermissions,
  usePlatformApp,
  usePlatformRuntime,
  useTenant,
} from '@platform/sdk';
import { Card } from '@platform/ui';
import { Badge } from '@platform/ui';
import { HealthStatus } from '../features/health/health-status';
import { appInfo } from '../lib/app-info';

export const Route = createFileRoute('/')({
  component: HomePage,
});

function HomePage() {
  return (
    <div className="space-y-8">
      <section className="space-y-2">
        <h1 className="text-3xl font-semibold tracking-tight">{appInfo.title}</h1>
        <p className="text-muted-foreground">
          Generated by the Platform MFE Application template — a production-ready
          React + Vite + TypeScript foundation.
        </p>
      </section>

      <section className="grid gap-4 md:grid-cols-2">
        <Card className="p-6">
          <h2 className="text-lg font-medium">Application identity</h2>
          <dl className="mt-4 space-y-2 text-sm">
            <div className="flex justify-between gap-4">
              <dt className="text-muted-foreground">ID</dt>
              <dd className="font-mono">{appInfo.id}</dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt className="text-muted-foreground">Mode</dt>
              <dd className="font-mono">{appInfo.mode}</dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt className="text-muted-foreground">Owner</dt>
              <dd className="font-mono">{appInfo.owner}</dd>
            </div>
          </dl>
          <div className="mt-4 flex flex-wrap gap-2">
            {appInfo.capabilities.map(capability => (
              <Badge key={capability} variant="outline">
                {capability}
              </Badge>
            ))}
            {appInfo.capabilities.length === 0 ? (
              <span className="text-sm text-muted-foreground">
                No capabilities requested.
              </span>
            ) : null}
          </div>
        </Card>

        <HealthStatus />
      </section>

      <PlatformCapabilities />

      <nav aria-label="Demos" className="flex flex-wrap gap-3">
        <Link
          to="/table"
          className="btn bg-primary text-primary-foreground hover:opacity-90"
        >
          Table demo
        </Link>
        <Link
          to="/form"
          className="btn bg-secondary text-secondary-foreground hover:opacity-90"
        >
          Form demo
        </Link>
      </nav>
    </div>
  );
}

/**
 * Demonstrates the @platform/sdk contracts this app was generated with:
 * identity/runtime are always available, while auth/permissions/tenant
 * report "unavailable" until a real provider is wired up for them (there is
 * none yet in standalone mode - see docs/platform-sdk.md in the control
 * plane repo for the full contract).
 */
function PlatformCapabilities() {
  const app = usePlatformApp();
  const { runtimeMode } = usePlatformRuntime();
  const { currentPath } = useNavigation();
  const auth = useAuth();
  const permissions = usePermissions();
  const tenant = useTenant();

  return (
    <Card className="p-6">
      <h2 className="text-lg font-medium">Platform capabilities</h2>
      <dl className="mt-4 space-y-3 text-sm">
        <div className="flex justify-between gap-4">
          <dt className="text-muted-foreground">App ID (via usePlatformApp)</dt>
          <dd className="font-mono">{app.id}</dd>
        </div>
        <div className="flex justify-between gap-4">
          <dt className="text-muted-foreground">Runtime mode</dt>
          <dd className="font-mono">{runtimeMode}</dd>
        </div>
        <div className="flex justify-between gap-4">
          <dt className="text-muted-foreground">Current path (via useNavigation)</dt>
          <dd className="font-mono">{currentPath}</dd>
        </div>
        <div className="flex justify-between gap-4">
          <dt className="text-muted-foreground">Auth</dt>
          <dd>
            <Badge variant={auth.status === 'ready' ? 'default' : 'outline'}>
              {auth.status === 'ready'
                ? auth.isAuthenticated
                  ? 'authenticated'
                  : 'unauthenticated'
                : 'unavailable'}
            </Badge>
          </dd>
        </div>
        <div className="flex justify-between gap-4">
          <dt className="text-muted-foreground">Permissions</dt>
          <dd>
            <Badge variant={permissions.status === 'ready' ? 'default' : 'outline'}>
              {permissions.status}
            </Badge>
          </dd>
        </div>
        <div className="flex justify-between gap-4">
          <dt className="text-muted-foreground">Tenant</dt>
          <dd>
            <Badge variant={tenant.status === 'ready' ? 'default' : 'outline'}>
              {tenant.status === 'ready' ? tenant.tenantName : 'unavailable'}
            </Badge>
          </dd>
        </div>
      </dl>
      {auth.status === 'unavailable' ? (
        <p className="mt-4 text-sm text-muted-foreground">{auth.reason}</p>
      ) : null}
    </Card>
  );
}
