import { createFileRoute, Link } from '@tanstack/react-router';

import { Card } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { HealthStatus } from '../features/health/health-status';
import { appInfo } from '../lib/app-info';

export const Route = createFileRoute('/')({
  component: HomePage,
});

function HomePage() {
  return (
    <div className="space-y-8">
      <section className="space-y-2">
        <h1 className="text-3xl font-semibold tracking-tight">{appInfo.title}</h1>
        <p className="text-muted-foreground">
          Generated by the Platform MFE Application template — a production-ready
          React + Vite + TypeScript foundation.
        </p>
      </section>

      <section className="grid gap-4 md:grid-cols-2">
        <Card className="p-6">
          <h2 className="text-lg font-medium">Application identity</h2>
          <dl className="mt-4 space-y-2 text-sm">
            <div className="flex justify-between gap-4">
              <dt className="text-muted-foreground">ID</dt>
              <dd className="font-mono">{appInfo.id}</dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt className="text-muted-foreground">Mode</dt>
              <dd className="font-mono">{appInfo.mode}</dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt className="text-muted-foreground">Owner</dt>
              <dd className="font-mono">{appInfo.owner}</dd>
            </div>
          </dl>
          <div className="mt-4 flex flex-wrap gap-2">
            {appInfo.capabilities.map(capability => (
              <Badge key={capability} variant="outline">
                {capability}
              </Badge>
            ))}
            {appInfo.capabilities.length === 0 ? (
              <span className="text-sm text-muted-foreground">
                No capabilities requested.
              </span>
            ) : null}
          </div>
        </Card>

        <HealthStatus />
      </section>

      <nav aria-label="Demos" className="flex flex-wrap gap-3">
        <Link
          to="/table"
          className="btn bg-primary text-primary-foreground hover:opacity-90"
        >
          Table demo
        </Link>
        <Link
          to="/form"
          className="btn bg-secondary text-secondary-foreground hover:opacity-90"
        >
          Form demo
        </Link>
      </nav>
    </div>
  );
}
