import platformApp from '../../platform-app.json';

/**
 * Typed view of the application's `platform-app.json` metadata. The file is
 * generated by the Backstage scaffolder from the values chosen when the
 * application was created, so these fields are stable at build time.
 */
export interface PlatformAppInfo {
  schemaVersion: string;
  id: string;
  title: string;
  mode: 'platform-mfe' | 'standalone' | 'standalone-and-mfe';
  owner: string;
  capabilities: string[];
  runtime: {
    type: string;
    status: string;
  };
}

export const appInfo = platformApp as PlatformAppInfo;
