/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as FormRouteImport } from './routes/form'
import { Route as TableRouteImport } from './routes/table'
{% if 'dashboard' in values.capabilities %}
import { Route as DashboardRouteImport } from './routes/dashboard'
{% endif %}
{% if 'settings' in values.capabilities %}
import { Route as SettingsRouteImport } from './routes/settings'
{% endif %}

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
{% if 'dashboard' in values.capabilities %}
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
{% endif %}
{% if 'settings' in values.capabilities %}
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
{% endif %}

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/form': typeof FormRoute
  '/table': typeof TableRoute
{% if 'dashboard' in values.capabilities %}
  '/dashboard': typeof DashboardRoute
{% endif %}
{% if 'settings' in values.capabilities %}
  '/settings': typeof SettingsRoute
{% endif %}
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/form': typeof FormRoute
  '/table': typeof TableRoute
{% if 'dashboard' in values.capabilities %}
  '/dashboard': typeof DashboardRoute
{% endif %}
{% if 'settings' in values.capabilities %}
  '/settings': typeof SettingsRoute
{% endif %}
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/form': typeof FormRoute
  '/table': typeof TableRoute
{% if 'dashboard' in values.capabilities %}
  '/dashboard': typeof DashboardRoute
{% endif %}
{% if 'settings' in values.capabilities %}
  '/settings': typeof SettingsRoute
{% endif %}
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/components' | '/form' | '/table'{% if 'dashboard' in values.capabilities %} | '/dashboard'{% endif %}{% if 'settings' in values.capabilities %} | '/settings'{% endif %}
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components' | '/form' | '/table'{% if 'dashboard' in values.capabilities %} | '/dashboard'{% endif %}{% if 'settings' in values.capabilities %} | '/settings'{% endif %}
  id: '__root__' | '/' | '/components' | '/form' | '/table'{% if 'dashboard' in values.capabilities %} | '/dashboard'{% endif %}{% if 'settings' in values.capabilities %} | '/settings'{% endif %}
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  FormRoute: typeof FormRoute
  TableRoute: typeof TableRoute
{% if 'dashboard' in values.capabilities %}
  DashboardRoute: typeof DashboardRoute
{% endif %}
{% if 'settings' in values.capabilities %}
  SettingsRoute: typeof SettingsRoute
{% endif %}
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
{% if 'dashboard' in values.capabilities %}
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
{% endif %}
{% if 'settings' in values.capabilities %}
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
{% endif %}
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  FormRoute: FormRoute,
  TableRoute: TableRoute,
{% if 'dashboard' in values.capabilities %}
  DashboardRoute: DashboardRoute,
{% endif %}
{% if 'settings' in values.capabilities %}
  SettingsRoute: SettingsRoute,
{% endif %}
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
