/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as FormRouteImport } from './routes/form'
import { Route as TableRouteImport } from './routes/table'
{% if 'authentication' in values.capabilities %}
import { Route as AuthenticationRouteImport } from './routes/authentication'
{% endif %}
{% if 'profile' in values.capabilities %}
import { Route as ProfileRouteImport } from './routes/profile'
{% endif %}
{% if 'rbac' in values.capabilities %}
import { Route as RbacRouteImport } from './routes/rbac'
{% endif %}
{% if 'dashboard' in values.capabilities %}
import { Route as DashboardRouteImport } from './routes/dashboard'
{% endif %}
{% if 'settings' in values.capabilities %}
import { Route as SettingsRouteImport } from './routes/settings'
{% endif %}
{% if 'reports' in values.capabilities %}
import { Route as ReportsRouteImport } from './routes/reports'
{% endif %}
{% if 'history' in values.capabilities %}
import { Route as HistoryRouteImport } from './routes/history'
{% endif %}
{% if 'audit-log' in values.capabilities %}
import { Route as AuditLogRouteImport } from './routes/audit-log'
{% endif %}

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
{% if 'authentication' in values.capabilities %}
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
{% endif %}
{% if 'profile' in values.capabilities %}
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
{% endif %}
{% if 'rbac' in values.capabilities %}
const RbacRoute = RbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
{% endif %}
{% if 'dashboard' in values.capabilities %}
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
{% endif %}
{% if 'settings' in values.capabilities %}
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
{% endif %}
{% if 'reports' in values.capabilities %}
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
{% endif %}
{% if 'history' in values.capabilities %}
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
{% endif %}
{% if 'audit-log' in values.capabilities %}
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
{% endif %}

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/form': typeof FormRoute
  '/table': typeof TableRoute
{% if 'authentication' in values.capabilities %}
  '/authentication': typeof AuthenticationRoute
{% endif %}
{% if 'profile' in values.capabilities %}
  '/profile': typeof ProfileRoute
{% endif %}
{% if 'rbac' in values.capabilities %}
  '/rbac': typeof RbacRoute
{% endif %}
{% if 'dashboard' in values.capabilities %}
  '/dashboard': typeof DashboardRoute
{% endif %}
{% if 'settings' in values.capabilities %}
  '/settings': typeof SettingsRoute
{% endif %}
{% if 'reports' in values.capabilities %}
  '/reports': typeof ReportsRoute
{% endif %}
{% if 'history' in values.capabilities %}
  '/history': typeof HistoryRoute
{% endif %}
{% if 'audit-log' in values.capabilities %}
  '/audit-log': typeof AuditLogRoute
{% endif %}
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/form': typeof FormRoute
  '/table': typeof TableRoute
{% if 'authentication' in values.capabilities %}
  '/authentication': typeof AuthenticationRoute
{% endif %}
{% if 'profile' in values.capabilities %}
  '/profile': typeof ProfileRoute
{% endif %}
{% if 'rbac' in values.capabilities %}
  '/rbac': typeof RbacRoute
{% endif %}
{% if 'dashboard' in values.capabilities %}
  '/dashboard': typeof DashboardRoute
{% endif %}
{% if 'settings' in values.capabilities %}
  '/settings': typeof SettingsRoute
{% endif %}
{% if 'reports' in values.capabilities %}
  '/reports': typeof ReportsRoute
{% endif %}
{% if 'history' in values.capabilities %}
  '/history': typeof HistoryRoute
{% endif %}
{% if 'audit-log' in values.capabilities %}
  '/audit-log': typeof AuditLogRoute
{% endif %}
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/form': typeof FormRoute
  '/table': typeof TableRoute
{% if 'authentication' in values.capabilities %}
  '/authentication': typeof AuthenticationRoute
{% endif %}
{% if 'profile' in values.capabilities %}
  '/profile': typeof ProfileRoute
{% endif %}
{% if 'rbac' in values.capabilities %}
  '/rbac': typeof RbacRoute
{% endif %}
{% if 'dashboard' in values.capabilities %}
  '/dashboard': typeof DashboardRoute
{% endif %}
{% if 'settings' in values.capabilities %}
  '/settings': typeof SettingsRoute
{% endif %}
{% if 'reports' in values.capabilities %}
  '/reports': typeof ReportsRoute
{% endif %}
{% if 'history' in values.capabilities %}
  '/history': typeof HistoryRoute
{% endif %}
{% if 'audit-log' in values.capabilities %}
  '/audit-log': typeof AuditLogRoute
{% endif %}
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/components' | '/form' | '/table'{% if 'authentication' in values.capabilities %} | '/authentication'{% endif %}{% if 'profile' in values.capabilities %} | '/profile'{% endif %}{% if 'rbac' in values.capabilities %} | '/rbac'{% endif %}{% if 'dashboard' in values.capabilities %} | '/dashboard'{% endif %}{% if 'settings' in values.capabilities %} | '/settings'{% endif %}{% if 'reports' in values.capabilities %} | '/reports'{% endif %}{% if 'history' in values.capabilities %} | '/history'{% endif %}{% if 'audit-log' in values.capabilities %} | '/audit-log'{% endif %}
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components' | '/form' | '/table'{% if 'authentication' in values.capabilities %} | '/authentication'{% endif %}{% if 'profile' in values.capabilities %} | '/profile'{% endif %}{% if 'rbac' in values.capabilities %} | '/rbac'{% endif %}{% if 'dashboard' in values.capabilities %} | '/dashboard'{% endif %}{% if 'settings' in values.capabilities %} | '/settings'{% endif %}{% if 'reports' in values.capabilities %} | '/reports'{% endif %}{% if 'history' in values.capabilities %} | '/history'{% endif %}{% if 'audit-log' in values.capabilities %} | '/audit-log'{% endif %}
  id: '__root__' | '/' | '/components' | '/form' | '/table'{% if 'authentication' in values.capabilities %} | '/authentication'{% endif %}{% if 'profile' in values.capabilities %} | '/profile'{% endif %}{% if 'rbac' in values.capabilities %} | '/rbac'{% endif %}{% if 'dashboard' in values.capabilities %} | '/dashboard'{% endif %}{% if 'settings' in values.capabilities %} | '/settings'{% endif %}{% if 'reports' in values.capabilities %} | '/reports'{% endif %}{% if 'history' in values.capabilities %} | '/history'{% endif %}{% if 'audit-log' in values.capabilities %} | '/audit-log'{% endif %}
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  FormRoute: typeof FormRoute
  TableRoute: typeof TableRoute
{% if 'authentication' in values.capabilities %}
  AuthenticationRoute: typeof AuthenticationRoute
{% endif %}
{% if 'profile' in values.capabilities %}
  ProfileRoute: typeof ProfileRoute
{% endif %}
{% if 'rbac' in values.capabilities %}
  RbacRoute: typeof RbacRoute
{% endif %}
{% if 'dashboard' in values.capabilities %}
  DashboardRoute: typeof DashboardRoute
{% endif %}
{% if 'settings' in values.capabilities %}
  SettingsRoute: typeof SettingsRoute
{% endif %}
{% if 'reports' in values.capabilities %}
  ReportsRoute: typeof ReportsRoute
{% endif %}
{% if 'history' in values.capabilities %}
  HistoryRoute: typeof HistoryRoute
{% endif %}
{% if 'audit-log' in values.capabilities %}
  AuditLogRoute: typeof AuditLogRoute
{% endif %}
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
{% if 'authentication' in values.capabilities %}
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
{% endif %}
{% if 'profile' in values.capabilities %}
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
{% endif %}
{% if 'rbac' in values.capabilities %}
    '/rbac': {
      id: '/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof RbacRouteImport
      parentRoute: typeof rootRouteImport
    }
{% endif %}
{% if 'dashboard' in values.capabilities %}
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
{% endif %}
{% if 'settings' in values.capabilities %}
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
{% endif %}
{% if 'reports' in values.capabilities %}
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
{% endif %}
{% if 'history' in values.capabilities %}
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
{% endif %}
{% if 'audit-log' in values.capabilities %}
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
{% endif %}
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  FormRoute: FormRoute,
  TableRoute: TableRoute,
{% if 'authentication' in values.capabilities %}
  AuthenticationRoute: AuthenticationRoute,
{% endif %}
{% if 'profile' in values.capabilities %}
  ProfileRoute: ProfileRoute,
{% endif %}
{% if 'rbac' in values.capabilities %}
  RbacRoute: RbacRoute,
{% endif %}
{% if 'dashboard' in values.capabilities %}
  DashboardRoute: DashboardRoute,
{% endif %}
{% if 'settings' in values.capabilities %}
  SettingsRoute: SettingsRoute,
{% endif %}
{% if 'reports' in values.capabilities %}
  ReportsRoute: ReportsRoute,
{% endif %}
{% if 'history' in values.capabilities %}
  HistoryRoute: HistoryRoute,
{% endif %}
{% if 'audit-log' in values.capabilities %}
  AuditLogRoute: AuditLogRoute,
{% endif %}
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
